const lang = {
    appTitle: "PDCA Management App",
    projectManagement: "Project Management",
    packManagement: "Pack Management",
    progressManagement: "Progress Management",
    createProject: "Create Project",
    projectName: "Project Name",
    projectDescription: "Project Description",
    projectKPI: "Project KPI",
    projectDueDate: "Due Date (hours)",
    addProject: "Add Project",
    existingProjects: "Existing Projects",
    delete: "Delete",
    createPack: "Create Pack",
    addPack: "Add Pack",
    existingPacks: "Existing Packs",
    plan: "Plan",
    do: "Do",
    check: "Check",
    act: "Act",
    done: "Done",
    undone: "Undone",
    linkName: "Link Name",
    linkHref: "Link URL",
    addLink: "Add Link",
    viewPacks: "View Packs",
    packsSummary: "Packs Summary",
    postToTwitter: "Post Project to Twitter",
    postPackToTwitter: "Post Pack to Twitter",
    sortByPDCAAsc: "Sort by PDCA Ascending",
    sortByPDCADesc: "Sort by PDCA Descending",
    sortByDueDateAsc: "Sort by Due Date Ascending",
    sortByDueDateDesc: "Sort by Due Date Descending",
    sortByStarsAsc: "Sort by Stars Ascending",
    sortByStarsDesc: "Sort by Stars Descending",
    sortByKPIAsc: "Sort by KPI Ascending",
    sortByKPIDesc: "Sort by KPI Descending",
    dueDate: "Due Date",
    update: "Update",
    current_price: "Current Price",
    target_price: "Target Price",
    objective_price: "Objective Price",
    priceDescription: "Objective priceDescription",
    memberManage: "Member Management",
    existingMembers: "Existing Members",
    name: "Name",
    position: "Position",
    link: "Link",
    addMember: "Add Member",
    add: "Add",
    delete: "Delete",
    languageIcon: "🇬🇧"
};
